// Mocks generated by Mockito 5.4.2 from annotations
// in interstellar_insight/test/features/characters/presentation/bloc/characters_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:interstellar_insight/core/errors/failure.dart' as _i6;
import 'package:interstellar_insight/core/usecase/usecase.dart' as _i8;
import 'package:interstellar_insight/features/characters/domain/entities/character.dart'
    as _i7;
import 'package:interstellar_insight/features/characters/domain/repositories/character_repository.dart'
    as _i2;
import 'package:interstellar_insight/features/characters/domain/usecases/get_all_characters.dart'
    as _i4;
import 'package:interstellar_insight/features/characters/domain/usecases/get_character_by_id.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCharacterRepository_0 extends _i1.SmartFake
    implements _i2.CharacterRepository {
  _FakeCharacterRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllCharacters].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCharacters extends _i1.Mock implements _i4.GetAllCharacters {
  MockGetAllCharacters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharacterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCharacterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CharacterRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Character>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Character>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Character>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Character>>>);
}

/// A class which mocks [GetCharacterById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCharacterById extends _i1.Mock implements _i9.GetCharacterById {
  MockGetCharacterById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharacterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCharacterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CharacterRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Character>> call(
          _i9.CharacterByIdParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Character>>.value(
            _FakeEither_1<_i6.Failure, _i7.Character>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Character>>);
}
